name: Lint and Format

on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.0'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yapf pylint

    - name: Run YAPF
      run: |
        yapf --recursive --in-place --style=google .

    - name: Check for changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "Auto-format code with YAPF"
          git push
        else
          echo "No changes to commit"

    - name: Run Pylint
      run: |
        pylint **/*.py
